import time
import math
import sys
import random
import os

def loading():
  print("\033[H\033[J")
  for i in range(1):
    os.system('clear')
    print("Loading")
    time.sleep(0.15)
    os.system('clear')
    print("Loading.")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading..")
    time.sleep(0.15)
    os.system('clear')
    print("Loading...")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading")
    time.sleep(0.15)
    os.system('clear')
    print("Loading.")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading..")
    time.sleep(0.15)
    os.system('clear')
    print("Loading...")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading")
    time.sleep(0.15)
    os.system('clear')
    print("Loading.")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading..")
    time.sleep(0.15)
    os.system('clear')
    print("Loading...")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading")
    time.sleep(0.15)
    os.system('clear')
    print("Loading.")
    time.sleep(0.15)  
    os.system('clear')
    print("Loading..")
    time.sleep(0.15)
    os.system('clear')
    print("Loading...")
    time.sleep(0.15)  
    os.system('clear')
    time.sleep(1)
